### ISSUE TITLE
The Caverns of Flame (S22) progress tracker

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/The_Earths_Gut#8]
- [ ] Fix travel map track (pick 1 of the 4 to use)
- [ ] Customize AI of enemy sides
- [ ] fine-tune enemy gold/income amounts
- [ ] give enemy leaders names
- [ ] do a better job controlling which monsters are allowed to do monster infighting (or just remove monster infighting entirely?)
- [ ] modify notes in objectives
- [ ] fix issue with there being 2 Dulatuses
- [ ] write some more opening dialogue
- [ ] write dialogue for encountering/killing various enemies
- [ ] script cutscene for finding the Sceptre of Fire
- [ ] script separate end cutscene

**Comment by cooljeanius** [comment]
For the last one, I need to figure out which enemy is the one picking it up in the first place... @knyghtmare thinks I should copy over the definition of the `{OBJ_POTION_HEALING}` macro and then reimplement to fit my needs, but Myrian (on Discord) thinks I should just hardcode the coordinates of the potions into the `[avoid]` portions of the enemy AI...

**Comment by cooljeanius** [comment]
ok so Myrian is @ashmyr now

**Comment by cooljeanius** [comment]
The whole "2 Dulatuses" thing is pretty much the only one that's preventing me from releasing it as-is; the rest of them can all be worked on after a release...

**Comment by cooljeanius** [comment]
`timeline.txt` has some info on some stuff this scenario will need, both in terms of gameplay (a dwarf-Lich) and the closing cutscene(s): https://github.com/cooljeanius/The_Earths_Gut/blob/master/timeline.txt
(some can be put off for an epilogue scenario after this one)

**Comment by cooljeanius** [comment]
So, I went and released 0.3.0 despite still having a few unchecked boxes here... those can be fixed in a followup release...

**Comment by cooljeanius** [comment]
@knyghtmare gave me one more: adjust the colors to be warmer, so I've added that to the list...

**Comment by cooljeanius** [comment]
> @knyghtmare gave me one more: adjust the colors to be warmer, so I've added that to the list...

ok that ought to be done by b64c92520d9996186101103955251b6f9a651367

**Comment by cooljeanius** [comment]
I don't think I'll be able to fully finish this until a post-BfW-1.16 release, so, postponing for now...

**Comment by cooljeanius** [comment]
I made a bit of progress on the end cutscene recently, but there's still a lot to be done on it, not to mention the entire epilogue scenario that's supposed to follow...

**Comment by cooljeanius** [comment]
as of [df8fcf4](https://github.com/cooljeanius/The_Earths_Gut/commit/df8fcf413e7ef7209a5da3faa30d6cd1683ce6c6) I'm going to say the first checkbox here is done

**Comment by cooljeanius** [comment]
Tempted to close this, but I'm not quite sure yet...

**Comment by cooljeanius** [comment]
So, for the closing cutscene, I need to decide on someone to ask Dulatus about the book that's supposed to go with the hammer... @Konrad22 any suggestions? Also did you notice any enemies picking up potions at all?

**Comment by cooljeanius** [comment]
Some of the stuff from #33 might actually go here instead

**Comment by cooljeanius** [comment]
1 more thing about this scenario from the forums: https://forums.wesnoth.org/viewtopic.php?p=680959#p680959
